/**
 * Generated by orval v6.28.1 🍺
 * Do not edit manually.
 * Modern Social Network API
 * REST API для современной социальной сети с поддержкой постов, комментариев, stories, чата и подписок
 * OpenAPI spec version: 1.0.0
 */
import type { Message } from './message';
import type { ConversationParticipant } from './conversationParticipant';

export interface Conversation {
  created_at?: string;
  id?: string;
  messages?: Message[];
  participants?: ConversationParticipant[];
  updated_at?: string;
}
