/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 */
import type { HandlersStoryResponse } from './handlersStoryResponse';

export interface HandlersUserStoriesResponse {
  avatar_url?: string;
  id?: string;
  stories?: HandlersStoryResponse[];
  username?: string;
}
