/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 */

export interface HandlersCreateUserRequest {
  email: string;
  first_name?: string;
  last_name?: string;
  /** @minLength 6 */
  password: string;
  username: string;
}
