/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Modern Social Network API
 * API for Modern Social Network
 * OpenAPI spec version: 1.0
 */
import type { HandlersActorInfo } from './handlersActorInfo';

export interface HandlersNotificationResponse {
  actor?: HandlersActorInfo;
  created_at?: string;
  id?: string;
  read?: boolean;
  target_id?: string;
  type?: string;
}
