/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Modern Social Network API
 * API for Modern Social Network
 * OpenAPI spec version: 1.0
 */

export interface HandlersActorInfo {
  avatar_url?: string;
  first_name?: string;
  id?: string;
  is_verified?: boolean;
  last_name?: string;
  username?: string;
}
