/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Modern Social Network API
 * API for Modern Social Network
 * OpenAPI spec version: 1.0
 */

export interface HandlersCreateUserRequest {
  email: string;
  first_name?: string;
  last_name?: string;
  /** @minLength 6 */
  password: string;
  username: string;
}
