/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 */

export interface HandlersUserDTO {
  avatar_url?: string;
  bio?: string;
  created_at?: string;
  email?: string;
  first_name?: string;
  followers_count?: number;
  following_count?: number;
  id?: string;
  is_2fa_enabled?: boolean;
  is_active?: boolean;
  is_verified?: boolean;
  last_name?: string;
  updated_at?: string;
  username?: string;
}
