/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 */

export interface HandlersUpdateUserRequest {
  avatar_url?: string;
  bio?: string;
  email?: string;
  first_name?: string;
  is_2fa_enabled?: boolean;
  is_active?: boolean;
  is_verified?: boolean;
  last_name?: string;
  password?: string;
  username?: string;
}
