/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 */

export interface HandlersPostResponse {
  comments_count?: number;
  content?: string;
  created_at?: string;
  id?: string;
  image_url?: string;
  likes_count?: number;
  user_id?: string;
}
