/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Modern Social Network API
 * API for Modern Social Network
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlersStoryResponse {
  created_at?: string;
  id?: string;
  media_type?: string;
  media_url?: string;
}
