/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Modern Social Network API
 * API for Modern Social Network
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlersNotificationResponse } from './internalHandlersNotificationResponse';

export interface InternalHandlersNotificationListResponse {
  notifications?: InternalHandlersNotificationResponse[];
  unread_count?: number;
}
