/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Modern Social Network API
 * API for Modern Social Network
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlersActorInfo } from './internalHandlersActorInfo'

export enum NotificationTypeEnum {
	FOLLOW = 'follow',
	LIKE = 'like',
	COMMENT = 'comment'
}

export interface InternalHandlersNotificationResponse {
	actor?: InternalHandlersActorInfo
	created_at?: string
	id?: string
	read?: boolean
	target_id?: string
	type?: NotificationTypeEnum
}
