/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Modern Social Network API
 * API for Modern Social Network
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlersPostResponse {
  comments_count?: number;
  content?: string;
  created_at?: string;
  id?: string;
  image_url?: string;
  likes_count?: number;
  user_id?: string;
}
