/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Modern Social Network API
 * REST API для современной социальной сети с поддержкой постов, комментариев, stories, чата и подписок
 * OpenAPI spec version: 1.0.0
 */
import type { Login200OneOf } from './login200OneOf';
import type { Login200OneOfTwo } from './login200OneOfTwo';

export type Login200 = Login200OneOf | Login200OneOfTwo;
