/**
 * Generated by orval v6.28.1 🍺
 * Do not edit manually.
 * Modern Social Network API
 * REST API для современной социальной сети с поддержкой постов, комментариев, stories, чата и подписок
 * OpenAPI spec version: 1.0.0
 */

export type Login200OneOfTwoStatus = typeof Login200OneOfTwoStatus[keyof typeof Login200OneOfTwoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Login200OneOfTwoStatus = {
  '2fa_required': '2fa_required',
} as const;
