/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Modern Social Network API
 * API for Modern Social Network
 * OpenAPI spec version: 1.0
 */

export type PostPostsBody = {
  /** Post content */
  content: string;
  /** Post image */
  image?: Blob;
};
