/**
 * Generated by orval v6.28.1 🍺
 * Do not edit manually.
 * Modern Social Network API
 * REST API для современной социальной сети с поддержкой постов, комментариев, stories, чата и подписок
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterRequest {
  email: string;
  /** @maxLength 50 */
  first_name?: string;
  /** @maxLength 50 */
  last_name?: string;
  /** @minLength 8 */
  password: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  username: string;
}
