/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Modern Social Network API
 * REST API для современной социальной сети с поддержкой постов, комментариев, stories, чата и подписок
 * OpenAPI spec version: 1.0.0
 */

export type StoryMediaType =
	(typeof StoryMediaType)[keyof typeof StoryMediaType]

export const StoryMediaType = {
	image: 'image',
	video: 'video',
} as const
