/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Modern Social Network API
 * REST API для современной социальной сети с поддержкой постов, комментариев, stories, чата и подписок
 * OpenAPI spec version: 1.0.0
 */

export interface User {
	avatar_url?: string
	bio?: string
	created_at?: string
	email?: string
	first_name?: string
	id?: string
	is_2fa_enabled?: boolean
	followers_count?: number
	following_count?: number
	is_active?: boolean
	is_verified?: boolean
	last_name?: string
	updated_at?: string
	username?: string
}
